version: '2.2'

services:
  zookeeper1:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      emqx-kafka-bridge:
    #volumes:
      #- ./zookeeper:/bitnami/zookeeper

  kafka1:
    image: 'bitnami/kafka:2.8.0'
    hostname: kafka1
    container_name: kafka1
    ports:
      - '9092:9092'
      - '9999:9999'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    #volumes:
      #- ./kafka:/bitnami/kafka
    networks:
      - my-network
    depends_on:
      - zookeeper1

networks:
  my-network:
    name: test-kafka
